Lesson 6 acceptance testing
mubat/asker_rails_course pull request #3
Opened 2021-08-14 14:28 UTC by mubat

2021-08-15 13:06 UTC, vkurennov requested changes
Кроме прочего, не реализована фича удаления ответа

2021-08-15 13:06 UTC, vkurennov commented on app/controllers/questions_controller.rb
> +    return redirect_to question_path(question) if question.user != current_user
1. return тут лишний, т.к. redirect_to прерывает выполнение метода
2. сравнивать лучше по user_id, чтобы не делать лишний запрос к базе на загрузку ассоциации
3. т.к. такое сравнение много где понадобится, то лучше вынести его в метод User#author_of? и вызывать в нужных местах (не забудь тесты модели на этот метод)

2021-08-15 13:06 UTC, vkurennov commented on app/views/answers/_list.html.slim
> +  -for answer in answers
лучше использовать each

2021-08-15 13:06 UTC, vkurennov commented on app/views/questions/index.html.slim
> +    -for question in @questions
используй each для итерации по коллекции

2021-08-15 13:06 UTC, vkurennov commented on app/views/questions/show.html.slim
> +-if question.user == current_user
замени на вызов метода `User#author_of?`

2021-08-15 13:06 UTC, vkurennov commented on app/views/questions/show.html.slim
> +  = render 'answers/list', answers: question.answers
если сделать паршл для одного ответа и назвать его answers/_answer.html.slim, то можно коллекцию выводить вот так:

`render question.answers`

2021-08-15 13:06 UTC, vkurennov commented on spec/acceptance/answer/view_answers_spec.rb
> +    expect(question_with_answers.answers.length).to be > 0
знаки >, < и == не работают в тестах, используй методоы eq,less_than, more_than

2021-08-16 18:30 UTC, mubat commented on app/controllers/answers_controller.rb
>  class AnswersController < ApplicationController
добавил

2021-08-16 18:32 UTC, mubat commented on app/controllers/answers_controller.rb
> +    flash[:alert] = "Answer can't be empty" unless @answer.save
поменял на рендер страницы вопроса. 
Как я вижу, должна открываться страница Вопроса, но в реальности URL содержит `/answers`. Как сделать так, чтобы при `render` был адрес страницы Вопроса, но при этом сохранить инстанс Ответа с ошибками в нём - не знаю

2021-08-16 19:19 UTC, mubat commented on app/controllers/questions_controller.rb
> +    return redirect_to question_path(question) if question.user != current_user
- без `return`  раньше у меня ругалось. Что-то говорилось про то, что нельзя в одном методе 2 раза вызывать `redirect_to`. Но по прошествию правок почему-то теперь этой ошибки нет. Не понял, почему так?
- проверку в отдельный метод вынес

2021-08-16 19:20 UTC, mubat commented on app/views/answers/_list.html.slim
> +  -for answer in answers
заменил

2021-08-16 19:20 UTC, mubat commented on app/views/questions/index.html.slim
> +    -for question in @questions
заменил

2021-08-16 19:20 UTC, mubat commented on app/views/questions/show.html.slim
> +-if question.user == current_user
заменил

2021-08-16 19:20 UTC, mubat commented on app/views/questions/show.html.slim
> +  = render 'answers/list', answers: question.answers
переделал на использование паршиала для модели

2021-08-16 19:23 UTC, mubat commented on spec/acceptance/answer/view_answers_spec.rb
> +    expect(question_with_answers.answers.length).to be > 0
что-то я не нашёл упоминаний про методы `less_than`, `more_than`, гугл молчит как партизан. И не работают у меня эти методы. 
При этом логические операторы спокойно работают. Я нашёл информацию здесь: https://relishapp.com/rspec/rspec-expectations/docs/built-in-matchers и здесь: https://rubydoc.info/gems/rspec-expectations/frames. 
В общем, поменял на более конкретное `eq`

2021-08-17 08:25 UTC, vkurennov approved these changes

2021-08-17 08:25 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +    redirect_to answer.question
редирект в общем-то отдинаковый в обоих случаях, тут хоршо бы сообщение доабавить в случае успеха/неуспеха

2021-08-17 08:25 UTC, vkurennov commented on app/models/user.rb
> +    question.user_id == id
почему question? тут может быть и ответ и что угодно. лучеш параметр назвать что-то вроде resource, item, object, т.е. как-то более универсально

2021-08-17 08:25 UTC, vkurennov commented on app/views/answers/_answer.html.slim
> +    -if current_user && current_user.author_of?(question)
тут можно избавиться от двойного условия, применив [safe navigation](https://mitrev.net/ruby/2015/11/13/the-operator-in-ruby/)

2021-08-17 08:25 UTC, vkurennov commented on app/views/questions/show.html.slim
> +-if current_user && current_user.author_of?(question)
тут тоже стоит применить safe navigation

2021-08-21 09:38 UTC, merged